package com.bkash.savings.migrator_dynamodb_pg.dynamodb_models.payment.dto;

public enum PaymentStatus {

    RPP_PAYMENT_WEBHOOK_SUCCEEDED,
    RPP_PAYMENT_WEBHOOK_FAILED,
    RPP_PAYMENT_SUCCEEDED,
    FI_PAYMENT_SEND_PENDING,
    FI_PAYMENT_SEND_SUCCEEDED,
    FI_PAYMENT_SEND_FAILED,
    SETTLEMENT_REQUIRED,
    RPP_SETTLEMENT_PENDING,
    RPP_REFUND_WEBHOOK_SUCCEEDED,
    RPP_REFUND_WEBHOOK_FAILED,
    RPP_REFUND_PENDING,
    RPP_REFUND_FAILED,
    RPP_REFUND_SUCCEEDED,
    FI_REFUND_CONFIRMATION_PENDING,
    FI_REFUND_CONFIRMATION_SUCCEEDED,
    FI_REFUND_CONFIRMATION_FAILED,
    UNKNOWN,
    SUCCEEDED_PAYMENT,
    CPS_INSTALLMENT_PENDING,
    CPS_INSTALLMENT_FAILED,
    FI_INSTALLMENT_PENDING,
    FI_INSTALLMENT_FAILED
}