package com.bkash.savings.models.postgres.account;

public enum SavingsAccountCurrentState {
    INIT_DB,
    PRODUCT_VALIDATION_FAILED,
    PRODUCT_VALIDATION_SUCCEEDED,
    PRODUCT_VALIDATION_PENDING,

    ORGANIZATION_VALIDATION_FAILED,
    ORGANIZATION_VALIDATION_SUCCEEDED,
    ORGANIZATION_VALIDATION_PENDING,

    E_KYC_FETCH_INFO_PENDING,
    E_KYC_FETCH_INFO_FAILED,
    E_KYC_FETCH_INFO_SUCCEEDED,

    E_KYC_NOMINEE_VALIDATION_FAILED,

    FI_SEND_KYC_PENDING,
    FI_SEND_KYC_SUCCEEDED,
    FI_SEND_KYC_FAILED,

    // TODO:
    // RPS successfully sent the request to the RPP, but the RPP is still processing the request.
    RPP_SUBSCRIPTION_PENDING,

    RPP_SUBSCRIPTION_FAILED,

    // RPP successfully processed the request and the subscription is active.
    // this is the final state of the savings account creation process.
    RPP_SUBSCRIPTION_SUCCEEDED,

    RPP_SUBSCRIPTION_CANCELLED,

    RPP_UNSUBSCRIBE_PENDING,
    RPP_UNSUBSCRIBE_SUCCEEDED,
    RPP_UNSUBSCRIBE_FAILED,

    RPP_PRE_MATURE_CANCEL_PENDING,
    RPP_PRE_MATURE_CANCEL_SUCCEEDED,

    RPP_SUBSCRIPTION_WEBHOOK_SUCCEEDED,
    RPP_SUBSCRIPTION_WEBHOOK_FAILED,

    FI_ACCOUNT_CREATION_PENDING,
    FI_ACCOUNT_CREATION_ACCEPTED_FOR_PROCESSING,
    FI_ACCOUNT_CREATION_SUCCEEDED,
    FI_ACCOUNT_CREATION_FAILED,
    FI_ACCOUNT_NUMBER_IS_MISSING,

    FI_ACCOUNT_DELETION_PENDING,
    FI_ACCOUNT_DELETION_FAILED,
    FI_ACCOUNT_DELETION_SUCCEEDED,

    FI_MATURITY_PENDING,
    FI_MATURITY_FAILED,
    FI_MATURITY_SUCCEEDED,

    FI_ACCOUNT_START_DATE_MISMATCHED,
    FI_ACCOUNT_END_DATE_MISMATCHED,
    FI_ACCOUNT_MATURITY_DATE_MISMATCHED,

    MATURED_BY_SCHEDULER_FAILED,
    MATURED_BY_SCHEDULER,
    MATURED_BY_SQS,

    CPS_PAYMENT_FAILED,
    CPS_PAYMENT_PENDING,
    CPS_PAYMENT_SUCCEEDED,

    RPP_SUBSCRIPTION_REQUEST_PENDING,
    RPP_SUBSCRIPTION_REQUEST_FAILED,
    RPP_SUBSCRIPTION_REQUEST_SUCCEEDED,
}
