package com.bkash.savings.models.dto.fi;

import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * Represents the transaction information for financial institutions and bKash systems.
 * This class contains common details about the transaction status, account information, amounts,
 * and other optional transaction metadata.
 * 
 * @author Mahmudul Hasan Rana
 * @since 2025-01-20
 */
@Data
@SuperBuilder(toBuilder = true)
@NoArgsConstructor
@AllArgsConstructor
public class XTransactionInfo {

    /**
     * The status of the transaction from the financial institution.
     * It could indicate the ACCEPTED or UNWANTED state of the transaction.
     */
    protected FiTransactionstatus fiTransactionStatus;

    /**
     * The account ID associated with the financial institution.
     * This is used to identify the account within the financial institution.
     */
    @JsonProperty("accountId")
    protected String fiAccountId;

    /**
     * The account number associated with the financial institution.
     * This field provides the account's unique number as recognized by the financial institution.
     */
    @JsonProperty("accountNo")
    protected String fiAccountNumber;

    /**
     * The transaction ID generated by bKash.
     * This ID is used to track the transaction within the bKash system.
     */
    @JsonProperty("trxId")
    protected String bkashTransactionId;

    /**
     * The transaction ID generated by the financial institution.
     * This field is optional but mandatory when {@code fiTransactionStatus} is ACCEPTED
     * and the transaction type is not DISBURSEMENT.
     */
    protected String fiTransactionId;

    /**
     * The date and time of the transaction from the financial institution.
     * This field is optional but mandatory when {@code fiTransactionStatus} is ACCEPTED
     * and the transaction type is not DISBURSEMENT.
     * <p>
     * Format: {@code yyyyMMddHHmmSS}
     * </p>
     */
    protected String fiTransactionDate;

    /**
     * The transaction amount.
     * This represents the monetary value involved in the transaction.
     */
    protected BigDecimal amount;

    /**
     * The installment plan number associated with the financial institution.
     * This field is used when the transaction is part of a specific installment plan.
     */
    @JsonProperty("fiInstallmentPlanNumber")
    protected String fiPlanNumber;

}
